version: "3"
services:
  frontendgenerator:
    build:
      context: ./frontend
    container_name: frontendgenerator
    volumes:
      - ./frontend/source:/home/app:rw
    working_dir: /home/app
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - APP_ENVIRONMENT=dev
    env_file:
      - ./environments.env
    volumes:
      - ./backend/source:/home/app:rw
      - ./frontend/source:/home/app/fe:ro
    ports:
      - "80:3000"
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
